<?php

declare(strict_types=1);

namespace App\Console\Commands;

use App\Services\ContractAbiService;
use Illuminate\Console\Command;

final class CacheContractAbis extends Command
{
    /**
     * The name and signature of the console command.
     *
     * @var string
     */
    protected $signature = 'explorer:cache-contract-abis';

    /**
     * The console command description.
     *
     * @var string
     */
    protected $description = 'Cache contract method signatures from php-crypto ABIs and regenerate the contracts lang file.';

    public function handle(ContractAbiService $service): void
    {
        $service->cache();

        $signatures = $service->getAllSignatures();

        $this->generateLangFile($signatures);

        $this->info(sprintf('Cached %d contract method signatures.', count($signatures)));
    }

    /**
     * @param array<string, string> $signatures
     */
    private function generateLangFile(array $signatures): void
    {
        ksort($signatures);

        $lines = [];
        foreach ($signatures as $hash => $signature) {
            $lines[] = sprintf("    '%s' => '%s',", $hash, addslashes($signature));
        }

        $content = <<<PHP
        <?php

        declare(strict_types=1);

        // This file is auto-generated by `php artisan explorer:cache-contract-abis`.
        // Do not edit manually. Method signatures are derived from arkecosystem/crypto ABIs.

        return [
        {$this->formatEntries($signatures)}
            'argument' => '[:index]: :value',
        ];

        PHP;

        file_put_contents(resource_path('lang/en/contracts.php'), $content);
    }

    /**
     * @param array<string, string> $signatures
     */
    private function formatEntries(array $signatures): string
    {
        $lines = [];
        foreach ($signatures as $hash => $signature) {
            $lines[] = "    '{$hash}' => '".addslashes($signature)."',";
        }

        return implode("\n", $lines)."\n";
    }
}
