/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "login": [],
    "login.store": [],
    "logout": [],
    "password.confirm": [],
    "password.confirmation": [],
    "password.confirm.store": [],
    "wysiwyg.twitter": [],
    "wysiwyg.upload-image": [],
    "wysiwyg.count-characters": [],
    "cropper.upload-image": [],
    "debugbar.openhandler": [],
    "debugbar.clockwork": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.telescope": [
        {
            "name": "id",
            "required": true
        }
    ],
    "debugbar.assets.css": [],
    "debugbar.assets.js": [],
    "debugbar.cache.delete": [
        {
            "name": "key",
            "required": true
        },
        {
            "name": "tags",
            "required": false
        }
    ],
    "dusk.login": [
        {
            "name": "userId",
            "required": true
        },
        {
            "name": "guard",
            "required": false
        }
    ],
    "dusk.logout": [
        {
            "name": "guard",
            "required": false
        }
    ],
    "dusk.user": [
        {
            "name": "guard",
            "required": false
        }
    ],
    "horizon.stats.index": [],
    "horizon.workload.index": [],
    "horizon.masters.index": [],
    "horizon.monitoring.index": [],
    "horizon.monitoring.store": [],
    "horizon.monitoring-tag.paginate": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.monitoring-tag.destroy": [
        {
            "name": "tag",
            "required": true
        }
    ],
    "horizon.jobs-metrics.index": [],
    "horizon.jobs-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.queues-metrics.index": [],
    "horizon.queues-metrics.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.index": [],
    "horizon.jobs-batches.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs-batches.retry": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.pending-jobs.index": [],
    "horizon.completed-jobs.index": [],
    "horizon.silenced-jobs.index": [],
    "horizon.failed-jobs.index": [],
    "horizon.failed-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.retry-jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.jobs.show": [
        {
            "name": "id",
            "required": true
        }
    ],
    "horizon.index": [
        {
            "name": "view",
            "required": false
        }
    ],
    "livewire.update": [],
    "livewire.upload-file": [],
    "livewire.preview-file": [
        {
            "name": "filename",
            "required": true
        }
    ],
    "ignition.healthCheck": [],
    "ignition.executeSolution": [],
    "ignition.updateConfig": [],
    "home": [],
    "validators": [],
    "validator-monitor": [],
    "blocks": [],
    "block": [
        {
            "name": "block",
            "required": true,
            "binding": "hash"
        }
    ],
    "transactions": [],
    "transaction": [
        {
            "name": "transaction",
            "required": true,
            "binding": "hash"
        }
    ],
    "top-accounts": [],
    "wallet": [
        {
            "name": "wallet",
            "required": true,
            "binding": "address"
        }
    ],
    "wallet.blocks": [
        {
            "name": "wallet",
            "required": true,
            "binding": "address"
        }
    ],
    "wallet.voters": [
        {
            "name": "wallet",
            "required": true,
            "binding": "address"
        }
    ],
    "wallet-old": [
        {
            "name": "wallet",
            "required": true,
            "binding": "address"
        }
    ],
    "statistics": [],
    "contact": [],
    "compatible-wallets": [],
    "exchanges": [],
    "webhooks": [],
    "currency.update": [],
    "theme.update": [],
    "navbar-search.index": [],
    "navbar-search.redirect": []
}
}
export {};
