<?php

declare(strict_types=1);

return [
    'height'          => 'Height',
    'network'         => 'Network',
    'supply'          => 'Supply',
    'market_cap'      => 'Market Cap',
    'search_explorer' => 'Search Explorer',

    'transaction' => [
        'id'        => 'ID',
        'timestamp' => 'Timestamp',
        'type'      => 'Type',
        'sender'    => 'Sender',
        'recipient' => 'Recipient',
        'amount'    => 'Amount',
        'fee'       => 'Fee',
    ],

    'block' => [
        'id'           => 'ID',
        'timestamp'    => 'Timestamp',
        'generated_by' => 'Generated By',
        'height'       => 'Height',
        'transactions' => 'Transactions',
        'tx'           => 'Tx',
        'amount'       => 'Amount',
        'fee'          => 'Fee',
    ],
];
