<?php

declare(strict_types=1);

return [
    'height'           => 'Height',
    'network'          => 'Network',
    'supply'           => 'Supply',
    'market_cap'       => 'Market Cap',
    'search_explorer'  => 'Search Explorer',
    'verified_address' => 'Verified Address',
    'exchange'         => 'Exchange',

    'block' => [
        'id'           => 'ID',
        'timestamp'    => 'Timestamp',
        'generated_by' => 'Generated By',
        'height'       => 'Height',
        'transactions' => 'Transactions',
        'tx'           => 'Tx',
        'amount'       => 'Amount',
        'fee'          => 'Fee',
    ],

    'transaction' => [
        'id'            => 'ID',
        'timestamp'     => 'Timestamp',
        'type'          => 'Type',
        'sender'        => 'Sender',
        'recipient'     => 'Recipient',
        'amount'        => 'Amount',
        'fee'           => 'Fee',
        'confirmations' => 'Confirmations',

        'bridgechain'           => 'Bridgechain',
        'business'              => 'Business',
        'delegate-registration' => 'Delegate Registration',
        'delegate-resignation'  => 'Delegate Resignation',
        'ipfs'                  => 'IPFS',
        'module'                => 'Module',
        'multi-payment'         => 'Multipayment',
        'multi-signature'       => 'Multisignature',
        'plugin'                => 'Plugin',
        'product'               => 'Product',
        'second-signature'      => 'Second Signature',
        'timelock'              => 'Timelock',
        'transfer'              => 'Transfer',
        'unvote'                => 'Unvote',
        'vote'                  => 'Vote',
        'vote-combination'      => 'Vote/Unvote',
    ],

    'wallet' => [
        'rank'    => 'Rank',
        'address' => 'Address',
        'info'    => 'Info',
        'balance' => 'Balance',
        'supply'  => 'Supply',
    ],
];
