<?php

declare(strict_types=1);

return [
    'height'           => 'Height',
    'network'          => 'Network',
    'supply'           => 'Supply',
    'market_cap'       => 'Market Cap',
    'search_explorer'  => 'Search Explorer',
    'verified_address' => 'Verified Address',
    'exchange'         => 'Exchange',

    'block' => [
        'id'           => 'ID',
        'timestamp'    => 'Timestamp',
        'generated_by' => 'Generated By',
        'height'       => 'Height',
        'transactions' => 'Transactions',
        'tx'           => 'Tx',
        'amount'       => 'Amount',
        'fee'          => 'Fee',
    ],

    'transaction' => [
        'id'        => 'ID',
        'timestamp' => 'Timestamp',
        'type'      => 'Type',
        'sender'    => 'Sender',
        'recipient' => 'Recipient',
        'amount'    => 'Amount',
        'fee'       => 'Fee',
    ],

    'wallet' => [
        'rank'    => 'Rank',
        'address' => 'Address',
        'info'    => 'Info',
        'balance' => 'Balance',
        'supply'  => 'Supply',
    ],
];
