<?php

declare(strict_types=1);

return [

    'address'                 => 'Address',
    'amount'                  => 'Amount',
    'balance_percentage'      => 'Supply', // Weird to call it supply
    'balance'                 => 'Balance',
    'block_forger'            => 'Forger',
    'block_height'            => 'Height',
    'block_id'                => 'ID',
    'confirmations'           => 'Confirmations',
    'exchange'                => 'Exchange',
    'fee'                     => 'Fee',
    'generated_by'            => 'Generated By',
    'last_block'              => 'Last Block',
    'productivity'            => 'Productivity',
    'rank'                    => 'Rank',
    'recipient'               => 'Recipient',
    'round_status'            => 'Status',
    'sender'                  => 'Sender',
    'slot_id'                 => 'ID',
    'slot_time'               => 'Forging Time',
    'timestamp'               => 'Timestamp',
    'transaction_count'       => 'Transaction Count',
    'transaction_id'          => 'ID',
    'username'                => 'Username',
    'verified_address'        => 'Verified Address',
    'votes'                   => 'Votes',
    'wallet_type'             => 'Info',
    'multi_signature'         => 'Multisignature',
    'second_signature'        => 'Second Signature',
];
