version: '2'
services:
  arkscan:
    image: ardenthq/arkscan
    container_name: arkscan
    restart: always
    ports:
      - '8898:8898'
    working_dir: /var/www/arkscan
    networks:
      - arkscan
    volumes:
      - arkscan:/var/www/arkscan
    tty: true
networks:
  arkscan:
volumes:
  arkscan:
    driver_opts:
      type: none
      device: $PWD/../
      o: bind 
