version: '3'
services:
  arkscan:
    image: ardenthq/arkscan
    labels:
        - "traefik.enable=true"
        - "traefik.http.middlewares.arkscan.retry.attempts=3"
        - "traefik.http.routers.arkscan.rule=Host(`${DOMAIN}`)"
        - "traefik.http.routers.arkscan.entrypoints=websecure"
        - "traefik.http.routers.arkscan.tls.certresolver=myresolver"
        - "traefik.http.services.arkscan.loadbalancer.server.port=8898"
        - "traefik.http.services.arkscan.loadbalancer.healthCheck.path=/"
        - "traefik.http.services.arkscan.loadbalancer.healthCheck.interval=10s"
        - "traefik.http.services.arkscan.loadbalancer.healthCheck.timeout=5s"
        
    restart: unless-stopped 
    working_dir: /var/www/arkscan
    networks:
      - traefik 
    volumes:
      - arkscan:/var/www/arkscan
    tty: true
networks:
  traefik:
      external:
          name: traefik_webgateway
volumes:
  arkscan:
    driver_opts:
      type: none
      device: $PWD/../../
      o: bind
