import { IMemoryWallet, IToken, ITokenTransfer, ITransaction, IWallet } from "@/types/generated";

export const CONTRACT_METHODS = {
    transfer: "a9059cbb",
    multipayment: "1234abcd",
    vote: "5678ef01",
    unvote: "9abcdef0",
    validator_registration: "11223344",
    validator_resignation: "55667788",
    validator_update: "99aabbcc",
    username_registration: "ddeeff00",
    username_resignation: "ff112233",
    approve: "095ea7b3",
    contract_deployment: "22222222",
    batch_transfer: "33333333",
};

export const makeWallet = (overrides: Partial<IWallet> = {}): IWallet => ({
    address: "wallet-address",
    balance: "1000000000000000000",
    nonce: "1",
    public_key: "pubkey123",
    isActive: true,
    isCold: false,
    isValidator: false,
    isLegacy: false,
    isDormant: false,
    isResigned: false,
    legacyAddress: null,
    username: null,
    hasUsername: false,
    isKnown: false,
    isOwnedByExchange: false,
    hasSecondSignature: false,
    votes: "0",
    productivity: 0,
    balancePercentage: 0,
    formattedBalanceTwoDecimals: "1.00",
    formattedBalanceFull: "1.000000000000000000",
    formattedBalanceFullWithoutSuffix: "1.000000000000000000",
    fiatValue: "1.00",
    totalForged: "0",
    attributes: {},
    vote: null,
    voteUrl: null,
    votePercentage: null,
    ...overrides,
});

export const makeMemoryWallet = (overrides: Partial<IMemoryWallet> = {}): IMemoryWallet => ({
    address: "wallet-address",
    publicKey: null,
    isContract: false,
    hasUsername: false,
    username: null,
    isValidator: false,
    ...overrides,
});

export const makeToken = (overrides: Partial<IToken> = {}): IToken => ({
    address: "token-address",
    name: "Test Token",
    symbol: "TT",
    decimals: 18,
    totalSupply: "1000000000000000000000",
    deploymentHash: "0xdeployhash",
    ...overrides,
});

export const makeTransaction = (overrides: Partial<ITransaction> = {}): ITransaction => ({
    hash: "0xabc123",
    block_hash: "0xblock123",
    block_number: 1,
    transaction_index: 0,
    timestamp: 1000000,
    nonce: 1,
    sender_public_key: "pubkey123",
    from: "sender-address",
    to: "recipient-address",
    value: "1000000000000000000",
    gas_price: "100",
    gas: "21000",
    status: true,
    gas_used: "100",
    gas_refunded: "0",
    deployed_contract_address: null,
    decoded_error: null,
    multiPaymentRecipients: [],
    amountFiat: "1.00",
    amountReceivedFiat: "1.00",
    feeFiat: "0.01",
    url: "https://example.com/tx/0xabc123",
    methodData: { functionName: null, methodId: null, arguments: [] },
    tokenApprovalDetails: null,
    validatorRegistration: null,
    votedFor: null,
    votedForUsername: null,
    sender: null,
    recipient: null,
    ...overrides,
});

export const makeTokenTransfer = (overrides: Partial<ITokenTransfer> = {}): ITokenTransfer => ({
    transaction_hash: "0xabc123",
    from: makeMemoryWallet({ address: "from-address" }),
    to: makeMemoryWallet({ address: "to-address" }),
    amount: 1.0,
    value: "1000000000000000000",
    block_number: 1,
    index: 0,
    token: makeToken(),
    transaction: makeTransaction(),
    ...overrides,
});
