<div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Timestamp</th>
                <th>Generated By</th>
                <th>Height</th>
                <th>Transactions</th>
                <th>Amount</th>
                <th>Fee</th>
            </tr>
        </thead>
        <tbody>
            @foreach($blocks as $block)
                <tr>
                    <td>{{ $block->id }}</td>
                    <td>{{ $block->timestamp }}</td>
                    <td>{{ $block->generator_public_key }}</td>
                    <td>{{ $block->height }}</td>
                    <td>{{ $block->number_of_transactions }}</td>
                    <td>{{ $block->total_amount }}</td>
                    <td>{{ $block->total_fee }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $blocks->links() }}
</div>
