<div>
    <table>
        <thead>
            <tr>
                <th>ID</th>
                <th>Timestamp</th>
                <th>Generated By</th>
                <th>Height</th>
                <th>Transactions</th>
                <th>Amount</th>
                <th>Fee</th>
            </tr>
        </thead>
        <tbody>
            @foreach($blocks as $block)
                <tr>
                    <td>{{ $block->id() }}</td>
                    <td>{{ $block->timestamp() }}</td>
                    <td>{{ $block->delegate() }}</td>
                    <td>{{ $block->height() }}</td>
                    <td>{{ $block->transactionCount() }}</td>
                    <td>{{ $block->amount() }}</td>
                    <td>{{ $block->fee() }}</td>
                </tr>
            @endforeach
        </tbody>
    </table>

    {{ $blocks->links() }}
</div>
