name: Format

on:
    pull_request:
        paths:
            - '**.css'
            - '**.js'
            - '**.php'
            - '**.vue'

jobs:
    php-cs-fixer:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GH_TOKEN }}

            - name: Setup PHP
              uses: shivammathur/setup-php@v2
              with:
                  php-version: '7.4'
                  extensions: mbstring, dom, fileinfo, intl, gd, imagick, bcmath, soap, zip, sqlite, pcov
                  coverage: pcov

            - name: Authenticate Nova
              run: composer config http-basic.nova.laravel.com ${{ secrets.NOVA_USERNAME }} ${{ secrets.NOVA_PASSWORD }}

            - name: Authenticate Packagist
              run: composer config http-basic.repo.packagist.com arkecosystem ${{ secrets.PACKAGIST_TOKEN }}

            - name: Authenticate Packagist
              run: composer config http-basic.repo.packagist.com arkecosystem ${{ secrets.PACKAGIST_TOKEN }}

            - name: Install
              run: composer install --no-ansi --no-interaction --no-scripts --no-suggest --no-progress --prefer-dist --optimize-autoloader

            - name: Run php-cs-fixer
              run: composer format

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'style: resolve style guide violations'
                  branch: ${{ github.head_ref }}

    prettier:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GH_TOKEN }}

            - name: Install
              run: yarn install --frozen-lockfile

            - name: Run prettier
              run: yarn run prettier --write 'resources/**/*.{css,js,vue}'

            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'style: resolve style guide violations'
                  branch: ${{ github.head_ref }}

    rustywind:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
              with:
                  ref: ${{ github.head_ref }}
                  token: ${{ secrets.GH_TOKEN }}

            - name: Format
              run: |
                  export PATH="$(yarn global bin):$PATH"
                  yarn global add rustywind
                  rustywind --write resources/views
            - uses: stefanzweifel/git-auto-commit-action@v4
              with:
                  commit_message: 'style: resolve style guide violations'
                  branch: ${{ github.head_ref }}
